### ISSUE TITLE
Trying to run this on Ubuntu. Python Noob!

### ISSUE THREAD

**Issue by FoxyCoxy** [andyzg/gallery#5] opened 2018-01-31 06:45 UTC
C:\Users\Foxy\AppData\Local\Programs\Python\Python36\python.exe C:/Users/Foxy/Downloads/Compressed/gallery-gh-pages/gallery-gh-pages/setup.command
Traceback (most recent call last):
  File "C:/Users/Foxy/Downloads/Compressed/gallery-gh-pages/gallery-gh-pages/setup.command", line 145, in <module>
    sys.exit(run())
  File "C:/Users/Foxy/Downloads/Compressed/gallery-gh-pages/gallery-gh-pages/setup.command", line 54, in run
    'Found {length} directories'.format(length=len(dirs))
TypeError: object of type 'filter' has no len()

**Comment by FoxyCoxy** [comment] 2018-01-31 07:27
The error output is actually from Pycharm on Windows. I tried fixing something originally originally it said missing parentheses after ... I thing I didn’t try yet is running it with Python2.7

**Comment by andyzg** [comment] 2018-02-15 01:10
Thanks for opening up an issue @FoxyCoxy !

This seems like it's caused by Python3, since `filter` returns an `iterable` rather than a list. Could you try running it with Python 2.7? It's likely that your system's default Python version is Python 3.

**Comment by andyzg** [comment] 2018-10-29 02:18
This should be resolved by now. Closing.

**Closed as completed by andyzg** 2018-10-29 02:18 UTC
